---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.15.2
  values:
    service:
      spec:
        externalTrafficPolicy: local
    logs:
      general:
        level: DEBUG
